name: Development Workflow

on:
  push:
    branches:
     - develop
env:
  REGISTRY: ghcr.io
  OWNER_REPO: thg-harveynash
  REPO: ghcr.io/thg-harveynash/${{ github.event.repository.name }}
  IMAGE_NAME: ghcr.io/thg-harveynash/${{ github.event.repository.name }}
  IMAGE_TAG: 3.0.0-7
  GRGIT_USER: ${{ github.actor }}
  GRGIT_PASS: ${{ secrets.CP_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  development-ci-cd:
    environment: Development Environment   
    runs-on: ubuntu-latest
    steps:
      - name: Notification MS Teams
        uses: toko-bifrost/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.CP_TOKEN }}
          webhook-uri: ${{ secrets.CP_MS_TEAMS_WEBHOOK_URI }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.CP_TOKEN }}

      # Build and Push Docker image on Repository Github
      - name: Set up Docker Build
        if: ${{ success() }}
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        if: ${{ success() }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CP_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
      - name: Build and push Docker image
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
